name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Angular Build & Deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v.1.3.1
        with:
          github_access_token: ${{ secrets.GH_PAGES_DEPLOY }}
          build_configuration: production
          base_href: https://eruecco87.github.io/tmi-angular/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/tmi
